[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
envy = "0.4.2"
reqwest = "0.11.18"
serde = "1.0.163"
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"
